baseurl             = "https://mikemcdonald.co"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Mike McDonald"
title               = "Mike McDonald"
pygmentsuseclasses  = true
pluralizelisttitles = false
googleAnalytics     = "UA-89729418-1"
logofile            = ""

[permalinks]
fixed = ":slug/"
blog  = "blog/:year/:month/:day/:slug/"
cities = "cities/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Travel"
weight                 = -100
identifier             = "travel"
url                    = "/travel/"

[[menu.main]]
name                   = "PM Course"
weight                 = -90
identifier             = "pm-course"
url                    = "/pm-course/"

[params]
author       = "Mike McDonald"
cachebuster  = true # add the current unix timestamp in query string for cache busting css assets
dateform     = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description  = "The personal site of Mike McDonald"
email        = "self@mikemcdonald.co"
faviconfile  = "favicon.ico"
github       = "//github.com/asciimike"
highlightjs  = true
lang         = "en"
linkedin     = "//linkedin.com/in/asciimike"
twitter      = "//twitter.com/asciimike"

# gravatar             = ""     # do not use in the same time as avatar
# avatar               = ""     # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# highlightjslanguages = ["go"] # additional languages not included in the "common" set

extracssfiles = [ "/css/override.css" ] # In your `static` directory, add/remove files as necessary.
