# This is a basic workflow to help you get started with Actions

name: Build and Deploy

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
      - name: Hugo build
        run: hugo --theme cocoa-hugo-theme
      - name: Upload /public
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
      - name: Upload firebase.json
        uses: actions/upload-artifact@v2
        with:
          name: firebase.json
          path: firebase.json
      - name: Upload .firebaserc
        uses: actions/upload-artifact@v2
        with:
          name: .firebaserc
          path: .firebaserc
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download /public
        uses: actions/download-artifact@v2
        with:
          name: public
      - name: Download firebase.json
        uses: actions/download-artifact@v2
        with:
          name: firebase.json
      - name: Download .firebaserc
        uses: actions/download-artifact@v2
        with:
          name: .firebaserc
      - name: Get firebase-tools
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
